version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.9

jobs:
  validate_orbs:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Validate orbs
          command: NAMESPACE=deep-impact-ag scripts/validate_orbs.sh

  publish_orbs:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: Install slack notifier
          command: |
            curl --location --output ./slack \
            https://github.com/cloudposse/slack-notifier/releases/download/0.2.0/slack-notifier_linux_amd64
            chmod +x ./slack
      - run:
          name: Publish orbs
          command: NAMESPACE=deep-impact-ag scripts/publish_orbs.sh

workflows:
  build:
    jobs:
      - validate_orbs:
          context: circleci-api
          filters:
            branches:
              ignore:
                - main
      - publish_orbs:
          context: circleci-api
          requires:
            - validate_orbs

